### ISSUE TITLE
This is the request not an issue

### ISSUE THREAD

**Issue by rahulshirphule** [kailash09dabhi/OmRecorder#1]
This library work like charm and also well maintained code.. But it would be great if you add Pause , Resume functionality.

agin this is not an issue but I posted here as I don't know where to give suggestion /  request.

Thanks for this good library .

**Comment by adrielcafe** [comment]
+1
A pause/resume feature would be awesome!

**Comment by kailash09dabhi** [comment]
Thanks @rahulshirphule! I will soon work on this feature.!

**Comment by kailash09dabhi** [comment]
close issue #3

**Comment by kailash09dabhi** [comment]
With the #3    pause / resume feature implemented
