### ISSUE TITLE
Not record the voice in many devices

### ISSUE THREAD

**Issue by developerGM** [kailash09dabhi/OmRecorder#12]
I am using this library in my project but many users contact me every day saying that own devices cannot record the voice. Why ? Are there android devices that can't record WAV format ?
One of these is for example Asus zenfone 2

**Comment by kailash09dabhi** [comment]
Please provide me complete details as this is too abstract when you say it is not recording. 
Elaborate in more detail and i will get back to you as soon as possible :)

**Comment by developerGM** [comment]
I have found the problem. 
When I finish to record I create an object MediaPlayer() to play immediately the recorded sound but still saving was not completed. It would not be possible to add un'interface like "OnRecordSuccess" to be sure to have the file?

**Comment by kailash09dabhi** [comment]
Sorry for late reply. I think you can check that on your end if file exist or not. also according to the implementation it must not take time. its very fast as only appending the header data to the PCM file. So there is no reason to have OnRecordSuccess callback.

**Comment by developerGM** [comment]
Don't worry kailash09dabhi. You are right but in my case, when I finish to record audio I immediatly init a MediaPlayer and set as source the recorded audio. The problem is that the time between finish to record and set source in media player is really short...and the file not exists. For this reason I prefer init a new Mediaplayer in a "onRecordSuccess"...I don't know if can you understand what I mean. Thanks for your support.

**Comment by kailash09dabhi** [comment]
if you think thats the issue then i think you can put a timer there.  Also please share demo code.

**Comment by kailash09dabhi** [comment]
Closes due to lack of activity.
Please , feel yourself free to reopen it.
