### ISSUE TITLE
Lossless Uncompressed Data

### ISSUE THREAD

**Issue by b16a** [kailash09dabhi/OmRecorder#13]
Hi,

Nice Library! 

This may be a stupid question but just to confirm this is indeed lossless uncompressed voice data being stored in the WAV file...?

Many thanks,

b16a

**Comment by kailash09dabhi** [comment]
Yeah correct! you may find more information here https://en.wikipedia.org/wiki/WAV

**Comment by b16a** [comment]
Thanks for the response!
