### ISSUE TITLE
Oneplus 3t issue with broken wav files

### ISSUE THREAD

**Issue by Flowrome** [kailash09dabhi/OmRecorder#15]
As the title says i can start a recording but when i try to reproduce it, that seems to be a broken file, i've tried in every third party player and it is broken. i thought that was a permission problem but it doesn't seems to be that.
can you look for it?

**Comment by kailash09dabhi** [comment]
Can you explain it in detail. Share the demo app so i can help you.

**Comment by Flowrome** [comment]
sorry for late answer, the demo is on playstore you can subscribe from here, https://play.google.com/apps/testing/flowrome.noteily . 
the problem is that with oxigen os rom on oneplus3t (i think also on oneplus3)  can't record a valid audio files, everything i've tried it seems that it doesn't work. on other Roms/devices works flawlessy, so maybe i was thinking that oxigen os has a specific method to record the .wav files. i really can't attach you a logcat because it doesn't give me an error, it just give me a broken file that cannot be played with any player available.

**Comment by kailash09dabhi** [comment]
i dont have oxigen os device so i cannot help here. But if you have you can debug the flow and can find out. Thanks
