### ISSUE TITLE
Problem while playing wav file in various devices.

### ISSUE THREAD

**Issue by manishSharmaJmd** [kailash09dabhi/OmRecorder#16]
Hi Kailash, 
You did a fantastic job! Cheers for that. I am fan of your coding man.

Let me explain you what others are getting issue like mine. 
In some devices like Moto G, Samsung on5 alomost that i have , i am able to play the WAV file that it creates after record.
but there are also many devices like LENOVO, MI note 3 which are not playing WAV file after recording finished. 

I am using MediaPlayer API in order to play file.
If i am not wrong then it seems problem is in write header part. WAV header is not appropriate writing for those devices to understand.

Do have a look at the link below :

https://github.com/roman10/roman10-android-tutorial/blob/master/AndroidWaveRecorder/src/roman10/tutorial/androidwaverecorder/WavAudioRecorder.java

This recorder demo works for all devices like LENOVO , MI etc.

Althrough VLC player and MX player both are able to play WAV file recorded by OM recorder in LEVENO , MI .

Hope this will help you to understand the issue with it.

**Comment by manishSharmaJmd** [comment]
Also i would like to know how can i increase MIC gain for recorder. in few devices recording volume is low.

**Comment by manishSharmaJmd** [comment]
Here are the audio files and hex dumps.
it has 2audio files and hex dump of each.
1 is recorded with the om recorder
and 2 is recorded using above mentioned recorder.
Hope it will help.
https://drive.google.com/file/d/0B_QtSGasHOUqel9FN3JwSThWY2s/view?usp=sharing

**Comment by kailash09dabhi** [comment]
Thank you very much for providing information, but I am nowadays super busy and so could not work on it in near future and as i dont have those devices to check what i can do here is only guessing so i think i will accept the pull request if you can show me that you have solved. But please make the branch for this and make a pull request. :) And Thanks for compliments! :)

**Comment by manishSharmaJmd** [comment]
Thanks Kailash for replying.
I am still figuring out the issue.

Even Windows media player is also able to play recording using OM recorder which is not playing on some devices.
I will sure let you know if fixed.
