### ISSUE TITLE
Storing File in Internal Storage

### ISSUE THREAD

**Issue by b16a** [kailash09dabhi/OmRecorder#17]
Hi 

Is it possible to store the WAV file on the private Internal storage allocated to the app...?

For example instead of using a File can one use the FileOutputStream ?

best,

b16a

**Comment by kailash09dabhi** [comment]
Currently OmRecorder is only taking File as parameter.
Why is FileOutputStream needed can you explain your usage?

**Comment by kailash09dabhi** [comment]
Closes due to lack of activity.
Please , feel yourself free to reopen it.
