### ISSUE TITLE
startRecording

### ISSUE THREAD

**Issue by nzala** [kailash09dabhi/OmRecorder#18]
```
wavsetupRecorder();
recorder.startRecording();

E/AudioRecord: Could not get audio input for record source 1, sample rate 44100, format 0x1, channel mask 0x10, session 161, flags 0
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
E/AndroidRuntime: FATAL EXCEPTION: Thread-367
                  Process: com PID: 3241
                  java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                      at android.media.AudioRecord.startRecording(AudioRecord.java:885)
                      at omrecorder.PullTransport$AbstractPullTransport.preparedSourceToBePulled(PullTransport.java:89)
                      at omrecorder.PullTransport$AbstractPullTransport.start(PullTransport.java:70)
                      at omrecorder.AbstractRecorder$1.run(AbstractRecorder.java:29)
                      at java.lang.Thread.run(Thread.java:818)
```

**Comment by nzala** [comment]
http://stackoverflow.com/questions/34860767/android-audiorecord-failing-when-calling-the-startrecording-method

**Comment by nzala** [comment]
[http://stackoverflow.com/questions/4342482/cannot-access-audiorecorder](url)

**Comment by nzala** [comment]
`E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord`

**Comment by kailash09dabhi** [comment]
pls show your wavsetupRecorder() method. It should be some illegal parameter not sure of though

**Comment by nzala** [comment]
```
private void wavsetupRecorder() {
        recorder = OmRecorder.wav(
                new PullTransport.Default(wavAudioSourcemic(), new PullTransport.OnAudioChunkPulledListener() {
                    @Override
                    public void onAudioChunkPulled(final AudioChunk audioChunk) {
                        progressbar.setProgress((int) (audioChunk.maxAmplitude()));
                    }
                }), wavfile());
    }

    private AudioSource wavAudioSourcemic() {
        smart = new AudioSource.Smart(MediaRecorder.AudioSource.MIC, AudioFormat.ENCODING_PCM_16BIT,
                AudioFormat.CHANNEL_IN_MONO, frequency);
        return smart;
    }
```

**Comment by nzala** [comment]
file is read-Owner, Group
write-Owner only
hw make
read and write-Owner, Group, Others

**Comment by kailash09dabhi** [comment]
Are you sure you have write permission to record & access external storage in manifest?

**Comment by nzala** [comment]
yes

**Comment by nzala** [comment]
hw make
read and write-Owner, Group, Others

**Comment by kailash09dabhi** [comment]
i am saying about permission in manifest.. android.permission.WRITE_EXTERNAl_STORAGE

**Comment by nzala** [comment]
yes i have
u need call recordInstance.release()? in [https://github.com/kailash09dabhi/OmRecorder/blob/master/om-recorder/src/main/java/omrecorder/AbstractRecorder.java](https://github.com/kailash09dabhi/OmRecorder/blob/master/om-recorder/src/main/java/omrecorder/AbstractRecorder.java)

**Comment by nzala** [comment]
hw make wav file
read and write-Owner, Group, Others

**Comment by kailash09dabhi** [comment]
This issue only happens due to permission.. See you are also requesting on runtime as from android 6.0 onwards we need to request permission on runtime.

**Comment by nzala** [comment]
i slved i called recordInstance.release()
but hw make wav file
read and write-Owner, Group, Others
i have made all permission on runtime.

**Comment by kailash09dabhi** [comment]
I am glad you solved it you can explain more here how you solved to help other users.
If you want to release the audio source you can do by simply like this:

     pulltransport.audioSource().release();

**Comment by nzala** [comment]
yes
`pulltransport.audioSource().release();`
but hw make wav file
read and write-Owner, Group, Others
i have made all permission on runtime.

**Comment by nzala** [comment]
if (recorder == null)
            return;
        if (recorder != null) {
            recorder.stopRecording();
            pulltransport.audioSource().release();
            recorder = null;
        }

**Comment by nzala** [comment]
jus add
```
if (recorder == null)
            return;
        if (recorder != null) {
            recorder.stopRecording();
            pulltransport.audioSource().release();
            recorder = null;
        }
```

**Comment by nzala** [comment]
make wav file
read and write-Owner, Group, Others
i have made all permission on runtime.

**Comment by kenchoong** [comment]
Hey @nzala , how you call  `pulltransport.audioSource().release();` in your project? cause I call event call for audioSource() to pullTransport.. can you give me some hint?
