### ISSUE TITLE
Android 6

### ISSUE THREAD

**Issue by phukhanhlee** [kailash09dabhi/OmRecorder#2]
When i record to 3 times , My app froze but it's not crashed. It is working great in android 5. Please check and fixed it.

**Comment by kailash09dabhi** [comment]
Is that issue happens with the sample provided ? If not then please provide me simple usecase. how you are using library with more information.

**Comment by phukhanhlee** [comment]
Ok. I have a listview, each item have button record:
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
.....
    record.setOnClickListener(recordClick);
.....
}

```
View.OnClickListener recordClick = new View.OnClickListener() {

    @Override
    public void onClick(View v) {
      mListener.recordVoicePath(position,mp3File);
};
```

In Activity , I implement recordVoicePath listener

```
@Override
public void recordVoicePath(int index, String path) {

    if (!hasPermission(RECORD_AUDIO)){
```

requestPermission(RECORD_AUDIO,RECORD_RESULT,getString(R.string.record_explanation));
        }else {

```
        if (!isRecording) {
            setupNoiseRecorder(ROOT_RECORD_SAVE + File.separator + path);
            mRecorder.startRecording();
            isRecording = true;
            mCaptionAdapter.mCurrentSelected = index;
            mCaptionAdapter.notifyDataSetChanged();
        } else {
            mRecorder.stopRecording();
            isRecording = false;
            mCaptionAdapter.mCurrentRecord = -1;
            mCaptionAdapter.mCurrentSelected = index;
            mCaptionAdapter.notifyDataSetChanged();
            mCurrentRecordIndex = -1;
        }
    }
}
```

And here is setupNoiseRecorder:
    private void setupNoiseRecorder(String filePath) {
File.separator+ filePath;
        String path = getRootPath() + File.separator+ filePath;
        // make sure the directory we plan to store the recording in exists
        File directory = new File(path).getParentFile();
        if (!directory.exists()) {
            directory.mkdirs();
        }

```
    mRecorder = OmRecorder.wav(
            new PullTransport.Noise(mic(), new PullTransport.OnAudioChunkPulledListener() {
                @Override public void onAudioChunkPulled(AudioChunk audioChunk) {
                    animateVoice((float) (audioChunk.maxAmplitude() / 200.0));
                }
            }, new WriteAction.Default(), new Recorder.OnSilenceListener() {
                @Override public void onSilence(long silenceTime) {
                    //Log.e("silenceTime", String.valueOf(silenceTime));
                    recordVoicePath(mCurrentRecordIndex,mCurrentRecordPath);
                }
            }, 200), file(filePath));
}
```

This code works great in android 5 but in android 6, after some recording, App will freeze. I think there are some problem in Record Library. Does i init OmRecorder in right ways ? Thanks

**Comment by phukhanhlee** [comment]
Thanks. Base on your implement to detect silence, i can do my jobs. So you can check again in android 6.
Here to record : http://www.edumobile.org/android/audio-recording-in-wav-format-in-android-programming/

And use your implement in Noise class to detect silence.

**Comment by kailash09dabhi** [comment]
i double checked and i don't find any problem on android 6. Please try to check on your side.
