### ISSUE TITLE
PullTransport

### ISSUE THREAD

**Issue by jpack1337** [kailash09dabhi/OmRecorder#21]
I recently got this log in one of our apps and wanted to reach out. It was a Motorola 6 that it's from.

```
Fatal Exception: java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
       at android.media.AudioRecord.startRecording(AudioRecord.java:894)
       at omrecorder.PullTransport$AbstractPullTransport.preparedSourceToBePulled(PullTransport.java:89)
       at omrecorder.PullTransport$AbstractPullTransport.start(PullTransport.java:70)
       at omrecorder.AbstractRecorder$1.run(AbstractRecorder.java:29)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by kailash09dabhi** [comment]
Are you using the latest version com.kailashdabhi:om-recorder:1.1.1 ?
Also please share the demo code which produce this issue.

**Comment by jpack1337** [comment]
Thank you for the quick response! I updated 1.1.0 to 1.1.1 and its still the same issue.

Here is the situation I use it with. The RapRecorder is initialized at this point. On most devices, this works perfectly! On Fabric, we are having quite a few crashes about it. It looks like 100% of these crashes are coming from 6.0.0 and 6.0.1, Samsung line phones.   I've attached the detailed report for your reference. 
```

   new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Process.setThreadPriority(Process.THREAD_PRIORITY_AUDIO);
                    mRapRecorder.startRecording();
                }catch (IllegalStateException e){
                    Amplitude.getInstance().logEvent("RCStudio - Illegal State Exception");
                }
            }
        }).start();
```


[me.rapchat.rapchat_issue_1583_crash_58DC065800BE000167B5F3A18177F855_37883c0e28084e6ba4236a97e68a0998_0_v1.txt](https://github.com/kailash09dabhi/OmRecorder/files/880259/me.rapchat.rapchat_issue_1583_crash_58DC065800BE000167B5F3A18177F855_37883c0e28084e6ba4236a97e68a0998_0_v1.txt)

**Comment by JeremyPacker** [comment]
* I have now updated and am still having the same issue

**Comment by jpack1337** [comment]
After some investigation into AudioRecord, I think my problem may be in the Frequency I use to start my AudioSource. Another possibility i'm thinking is it could possibly be the CHANNEL_IN_STEREO is not supported on every phone and causing it to crash?

    //Recording Methods
    private AudioSource mic() {
        return new AudioSource.Smart(MediaRecorder.AudioSource.DEFAULT  , AudioFormat.ENCODING_PCM_16BIT,
                AudioFormat.CHANNEL_IN_STEREO, 44100);
    }

I found this article that had suggested looping through to get the correct device but not sure if that is reasonable.

**Comment by kailash09dabhi** [comment]
It happens on android marshmallow means you are not handling runtime permission! 
Please check developers.android website for implementation. You should request runtime permission.

Please feel free to reopen if still it exist :)

**Comment by nzala** [comment]
add

if (recorder == null)
            return;
        if (recorder != null) {
            recorder.stopRecording();
            pulltransport.audioSource().release();
            recorder = null;
        }
@jpack1337

**Comment by jpack1337** [comment]
Hey @nzala , did this solve the issue for you?

Is this for when you stop recording only? I have noticed our issue with Start Recording too

**Comment by jpack1337** [comment]
Hey @kailash09dabhi , would you be open to discuss my project?  We are still having this issue in a majority of devices, even after requesting permissions. Looking for some extra help and couldn't figure out a way to contact you. Do you do contract work?

**Comment by nzala** [comment]
yes i have @jpack1337 
u need call recordInstance.release().

**Comment by kailash09dabhi** [comment]
Sorry for late reply :( 
@jpack1337 you have to release recorder properly and i think @nzala  has already shown the solution.
If you start the recording you have to properly release the recorder too.! 
@jpack1337 My email is already on github you can contact me :)

**Comment by kenchoong** [comment]
> add
> 
> if (recorder == null)
> return;
> if (recorder != null) {
> recorder.stopRecording();
> pulltransport.audioSource().release();
> recorder = null;
> }
> @jpack1337



And this: 

> yes i have @jpack1337
> u need call recordInstance.release().

Life saving answer.. Thank you very much
