### ISSUE TITLE
Record Pcm Audio

### ISSUE THREAD

**Issue by darkerhp** [kailash09dabhi/OmRecorder#22]
Hi kailash09dabhi. Thanks for your lib.
I have already use your lib to record .wav Audio. Its ok
But I do not know how can I record Pcm Audio file (.amr, .3gp?), the output file has data, but it can not play or read.
Here is my code: 
recorder = OmRecorder.pcm(
                        new PullTransport.Default(RecorderUtil.getMic(source, channel, sampleRate)),
                        new File("path to my .amr file"));
Where is my wrong?

**Comment by darkerhp** [comment]
Oh. I am so sorry, I have not read you example.

**Comment by kailash09dabhi** [comment]
ok nice let me close then :)
