### ISSUE TITLE
continue recording Audio

### ISSUE THREAD

**Issue by nzala** [kailash09dabhi/OmRecorder#23]
Audio Filecontinues existing record also

**Comment by kailash09dabhi** [comment]
Can you please elaborate more?

**Comment by nzala** [comment]
Recorder to append to an existing audio file instead of starting it over from the beginning

**Comment by kailash09dabhi** [comment]
Can you explain the usage of it? As already the pause() and resume() would do what you want.

**Comment by nzala** [comment]
continue Record to an existing audio file which has finished

**Comment by kailash09dabhi** [comment]
Actually if you choose the existing audio file for recording, then it will simply overwrite it.
I dont find it useful enough as I think writing on existing file over and over again would increase the size of file ! Anyway I welcome you to create pull request with your description.
