### ISSUE TITLE
Include NoiseSuppressor with AudioRecord

### ISSUE THREAD

**Issue by manankalra** [kailash09dabhi/OmRecorder#25]
![NoiseSuppressor](https://developer.android.com/reference/android/media/audiofx/NoiseSuppressor.html)

**Comment by manankalra** [comment]
![NoiseSuppressor](https://developer.android.com/reference/android/media/audiofx/NoiseSuppressor.html)

**Comment by kailash09dabhi** [comment]
Ok nice suggestion I will add this :)

**Comment by manankalra** [comment]
Other than that, features like ![LoudnessEnhancer](https://developer.android.com/reference/android/media/audiofx/LoudnessEnhancer.html) are also worth including, if we want to reduce cross-talk and background noise from the recorded file.

**Comment by kailash09dabhi** [comment]
Ok that would be great. I welcome you to make pull request. :)
