### ISSUE TITLE
How can I get audio waveform from recording sound？

### ISSUE THREAD

**Issue by fouriertry** [kailash09dabhi/OmRecorder#26]
Hello,I want to get audio waveform from recording sound,and I found that the method onAudioChunkPulled() can return AudioChunk, can I draw a wave with audiochunk.toShorts()?

**Comment by kailash09dabhi** [comment]
Yes obviously you can use AudioChunk to draw the wave form. AudioChunk is the data which fetched from AudioSource on every pull.
