### ISSUE TITLE
could not build OutputStream from this file 

### ISSUE THREAD

**Issue by Zerde** [kailash09dabhi/OmRecorder#33]
Hi, I am getting `could not build OutputStream from this file `  error on devices with android 5.1.1 and 8.0.0
it is from the ` private OutputStream outputStream(File file) ` method ,when starting recording

But when I copied the the method to my MainActivity, and called it whith exact same file(file name/directory), it didn't throw any error

Any idea what could be the problem?

**Comment by vdaita** [comment]
I am having the same issue. What did you do to solve it?

**Comment by vdaita** [comment]
Oh, figured it out.

**Comment by josmilan** [comment]
@vdaita What was the solution?
