### ISSUE TITLE
how to get MaxAmplitud ? thanks!

### ISSUE THREAD

**Issue by hsj-xiaokang** [kailash09dabhi/OmRecorder#34]

**Comment by karimatwa** [comment]
new PullTransport.OnAudioChunkPulledListener() {
              @Override
              public void onAudioChunkPulled(AudioChunk audioChunk) {
                   //audioChunk.maxAmplitude();
              }
          };

**Comment by kailash09dabhi** [comment]
Yes @karimatwa already given the answer! 
you have to use `audioChunk.maxAmplitude() `.
