### ISSUE TITLE
Don't understand README

### ISSUE THREAD

**Issue by leshark** [kailash09dabhi/OmRecorder#39]
`recorder = OmRecorder.wav(
        new PullTransport.Default(mic(), new PullTransport.OnAudioChunkPulledListener() {
          @Override public void onAudioChunkPulled(AudioChunk audioChunk) {
            animateVoice((float) (audioChunk.maxAmplitude() / 200.0));
          }
        }), file());`
What should be in animateVoice() method? i don't see any implementation of it!

**Comment by iman2420** [comment]
@leshark like this:

`private void animateVoice(final float maxPeak) {
    recordButton.animate().scaleX(1 + maxPeak).scaleY(1 + maxPeak).setDuration(10).start();
}`

**Comment by leshark** [comment]
I’ve waited for 4 years! Finally! (Really, not, I do not even write for android anymore XD)
But still, hope this will help someone

**Comment by iman2420** [comment]
@leshark I answered for exactly this reason, good luck
