### ISSUE TITLE
How to get getMaxAmplitude() for voice level

### ISSUE THREAD

**Issue by rahulshirphule** [kailash09dabhi/OmRecorder#6]
Hi Kailash,

how to use getMaxAmplitude() which is available for MediaRecorder class but how to acces this in your library. 

And yes thanks for Pause/Resume feature :)

Thanks.

**Comment by kailash09dabhi** [comment]
Its already on project page's readme. The AudioChunk class has method for max amplitude.

``` java

     OmRecorder.wav(
      new PullTransport.Default(mic(), new PullTransport.OnAudioChunkPulledListener() {
        @Override public void onAudioChunkPulled(AudioChunk audioChunk) {
          animateVoice((float) (audioChunk.maxAmplitude() / 200.0));  <------
        }
      }), file())
```
