### ISSUE TITLE
Issue about MaxAmplitude

### ISSUE THREAD

**Issue by cwfei** [kailash09dabhi/OmRecorder#9]
Hi there, currently I'm using default MediaRecord.getMaxAmplitude() to draw canvas base on the amplitude received. My codes below:

```
`Runnable updateVisualizer = new Runnable() {
    @Override
    public void run() {
        // get the current amplitude
        int x = mRecorder.getMaxAmplitude();
        visualizerView.addAmplitude(x); // update the VisualizeView
        visualizerView.invalidate(); // refresh the VisualizerView

        // update in 40 milliseconds
        handler.postDelayed(this, 40);
    }
    };`
```

I run the handler above when recording is start, however, by using your library I have no idea how to implement such handler using the MaxAmplitude return by AudioChunk, please help.

**Comment by kailash09dabhi** [comment]
possible duplicate #6 
Please check it cause you have to define the OnAudioChunkPulledListener which is responsible giving you AudioChunk and then you can get Max Amplitude from AudioChunk easily by calling like this:

``` java
audioChunk.maxAmplitude() 

```
